# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFDItHkCgbmUsTbmB_RMwmo1Epyvm4Nu
"""

import numpy as np
import matplotlib.pyplot as plt
import math
from scipy.integrate import solve_ivp

def runge_kutta_4_system_vector(f, x0, y0_vector, x_end, h):
    xn = [x0]
    yn = [np.array(y0_vector, dtype=float)]

    x = x0
    y = np.array(y0_vector, dtype=float)

    while x < x_end:
        h_step = min(h, x_end - x)

        k1 = h_step * f(x, y)
        k2 = h_step * f(x + h_step/2, y + k1/2)
        k3 = h_step * f(x + h_step/2, y + k2/2)
        k4 = h_step * f(x + h_step, y + k3)

        y = y + (k1 + 2*k2 + 2*k3 + k4) / 6
        x += h_step

        xn.append(x)
        yn.append(y.copy())

    return np.array(xn), np.array(yn)

def solve_system_rk4(x0, y10, y20, x_end, h):
    def f1(x, y):
        y1, y2 = y
        if x <= 0:
            return 0
        return y2 * math.log(x)

    def f2(x, y):
        y1, y2 = y
        return y1 + y2**2

    def f_system(x, y_vector):
        y1, y2 = y_vector

        dy1dx = f1(x, (y1, y2))
        dy2dx = f2(x, (y1, y2))

        return np.array([dy1dx, dy2dx])

    x_vals, y_vectors = runge_kutta_4_system_vector(f_system, x0, [y10, y20], x_end, h)

    y1_vals = y_vectors[:, 0]
    y2_vals = y_vectors[:, 1]

    return x_vals, y1_vals, y2_vals

def solve_with_scipy(x0, y10, y20, x_end, h):
    def system_ode(x, y):
        y1, y2 = y
        if x <= 0:
            dy1dx = 0
        else:
            dy1dx = y2 * math.log(x)
        dy2dx = y1 + y2**2
        return [dy1dx, dy2dx]

    solution = solve_ivp(
        system_ode,
        [x0, x_end],
        [y10, y20],
        method='DOP853',
        rtol=1e-12,  # Очень высокая точность
        atol=1e-12,
        dense_output=True
    )


    x_vals = np.arange(x0, x_end + h/2, h)
    y_interp = solution.sol(x_vals)

    return x_vals, y_interp[0], y_interp[1]

def runge_error_estimate(y_h, y_h2, p=4):
    error_estimate = np.abs(y_h - y_h2) / (2**p - 1)
    return error_estimate

def get_value_at_point(x_array, y_array, point):
    """Получить значение функции в заданной точке (линейная интерполяция)"""
    idx = np.searchsorted(x_array, point) - 1
    if idx < 0:
        idx = 0
    if idx >= len(x_array) - 1:
        idx = len(x_array) - 2

    x1, x2 = x_array[idx], x_array[idx + 1]
    y1, y2 = y_array[idx], y_array[idx + 1]

    if x2 == x1:
        return float(y1)

    t = (point - x1) / (x2 - x1)
    return float(y1 + t * (y2 - y1))

a, b = 1.0, 4.0
h = 0.1
y1_a, y2_a = -2.0, -1.0

x_vals, y1_vals, y2_vals = solve_system_rk4(a, y1_a, y2_a, b, h)
x_scipy, y1_scipy, y2_scipy = solve_with_scipy(a, y1_a, y2_a, b, h)

print("Значения по методу Рунге-Кутты: \n","x_values: \n",x_vals, "\n y1_values: \n", y1_vals, "\n y2_values: \n", y2_vals, "\n")
int_points = [1, 2, 3, 4]
results = {}
results_s = {}

def find_nearest_index(array, value):
        idx = (np.abs(array - value)).argmin()
        return idx

for point in int_points:
    idx = find_nearest_index(x_vals, point)
    x_found = x_vals[idx]
    y1_found = y1_vals[idx]
    y2_found = y2_vals[idx]
    y1_s_found = y1_scipy[idx]
    y2_s_found = y2_scipy[idx]
    results[point] = (x_found, y1_found, y2_found)
    results_s[point] = (x_found, y1_s_found, y2_s_found)

print("Результаты для метода Рунге-Кутты:")
print(f"{'x':>6} {'y1(x)':>15} {'y2(x)':>15}")
print("-" * 60)

for point in int_points:
        x_found, y1_val, y2_val = results[point]
        print(f"{point:>6.0f} {y1_val:>15.8f} {y2_val:>15.8f}")

print("\n Значения по solve_imp","x_values: \n",x_scipy, "\n y1_values: \n", y1_scipy, "\n y2_values: \n", y2_scipy, "\n")

print("\n Результаты через solve_imp:")
print(f"{'x':>6} {'y1(x)':>15} {'y2(x)':>15}")
print("-" * 60)

for point in int_points:
        x_found, y1_sc, y2_sc = results_s[point]
        print(f"{point:>6.0f} {y1_sc:>15.8f} {y2_sc:>15.8f}")

y1_for_interpolation = [results[p][1] for p in int_points]
y1_scipy_check = [abs(results[p][1] - results_s[p][1]) for p in int_points]

y1_lagrange_values = np.array(y1_for_interpolation, dtype=float)
diviations = np.array(y1_scipy_check, dtype=float)
print("\n Разница со встроенной функцией в целых x: \n", diviations)

#Проверка точности по правилу Рунге

x_h, y1_h, y2_h = solve_system_rk4(a, y1_a, y2_a, b, h)
x_h2, y1_h2, y2_h2 = solve_system_rk4(a, y1_a, y2_a, b, h/2)
x_h4, y1_h4, y2_h4 = solve_system_rk4(a, y1_a, y2_a, b, h/4)

y1_h_points = np.array([get_value_at_point(x_h, y1_h, p) for p in int_points], dtype=float)
y1_h2_points = np.array([get_value_at_point(x_h2, y1_h2, p) for p in int_points], dtype=float)
y1_h4_points = np.array([get_value_at_point(x_h4, y1_h4, p) for p in int_points], dtype=float)

print("\n Оценка погрешности для метода Рунге-Кутты по правилу Рунге: ")
error_y1_h = runge_error_estimate(y1_h_points, y1_h2_points, p=4)
print(error_y1_h, "\n")

x_h, y1_h, y2_h = solve_with_scipy(a, y1_a, y2_a, b, h)
x_h2, y1_h2, y2_h2 = solve_with_scipy(a, y1_a, y2_a, b, h/2)
x_h4, y1_h4, y2_h4 = solve_with_scipy(a, y1_a, y2_a, b, h/4)

y1_h_points = np.array([get_value_at_point(x_h, y1_h, p) for p in int_points], dtype=float)
y1_h2_points = np.array([get_value_at_point(x_h2, y1_h2, p) for p in int_points], dtype=float)
y1_h4_points = np.array([get_value_at_point(x_h4, y1_h4, p) for p in int_points], dtype=float)

print("\n Оценка погрешности для solve_ivp по правилу Рунге: ")
error_y1_h_p4 = runge_error_estimate(y1_h_points, y1_h2_points, p=4)
print(error_y1_h_p4, "\n")

print("\n Значения y1 для дальнейшей интерполяции Лагранжа: ",y1_lagrange_values)

y1_prime = np.gradient(y1_vals, x_vals)
y2_prime = np.gradient(y2_vals, x_vals)

plt.figure(figsize=(10, 6))
plt.plot(x_vals, y1_vals, 'o-', label=f'y1')
plt.plot(x_vals, y2_vals, '.-', label=f'y2')
plt.plot(x_vals, y1_prime, 'o-', label=f"y1'")
plt.plot(x_vals, y2_prime, '.-', label=f"y2'")
plt.xlabel('x')
plt.ylabel('y')
plt.title('Решение методом Рунге-Кутты 4-го порядка')
plt.legend()
plt.grid(True)
plt.show()

def lagrange_interpolation(x_points, y_points, x_values):

    # Преобразуем входные данные в массивы numpy
    x_points = np.asarray(x_points, dtype=float)
    y_points = np.asarray(y_points, dtype=float)
    x_values = np.asarray(x_values, dtype=float)

    # Проверка входных данных
    if len(x_points) != len(y_points):
        raise ValueError(f"Количество x-точек ({len(x_points)}) должно совпадать с количеством y-точек ({len(y_points)})")

    if len(x_points) == 0:
        raise ValueError("Массивы точек не могут быть пустыми")

    if len(x_points) == 1:
        # Если только одна точка, полином - константа
        return np.full_like(x_values, y_points[0])

    # Проверка на уникальность узлов интерполяции
    if len(np.unique(x_points)) != len(x_points):
        raise ValueError("Узлы интерполяции должны быть уникальными")

    # Если x_values - скаляр, преобразуем в массив
    is_scalar = x_values.ndim == 0
    x_values = np.atleast_1d(x_values)

    n = len(x_points)
    result = np.zeros_like(x_values, dtype=float)

    # Основной цикл интерполяции
    for i in range(n):
        # Вычисляем базисный полином Лагранжа l_i(x)
        term = np.ones_like(x_values, dtype=float) * y_points[i]

        for j in range(n):
            if i != j:
                term *= (x_values - x_points[j]) / (x_points[i] - x_points[j])

        result += term

    # Возвращаем результат в том же формате, что и вход
    return result[0] if is_scalar else result

def lagrange_basis_polynomials(x_points, x_values):

    x_points = np.asarray(x_points, dtype=float)
    x_values = np.asarray(x_values, dtype=float)

    n = len(x_points)
    m = len(x_values)
    basis = np.zeros((n, m), dtype=float)

    for i in range(n):
        basis[i] = np.ones(m, dtype=float)
        for j in range(n):
            if i != j:
                basis[i] *= (x_values - x_points[j]) / (x_points[i] - x_points[j])

    return basis

def lagrange_coefficients(x_points, y_points):

    x_points = np.asarray(x_points, dtype=float)
    y_points = np.asarray(y_points, dtype=float)
    n = len(x_points)

    # Инициализируем массив коэффициентов
    coefficients = np.zeros(n, dtype=float)

    for i in range(n):
        # Получаем базисный полином l_i(x)
        poly = np.array([1.0], dtype=float)  # Начинаем с константы 1

        for j in range(n):
            if i != j:
                # Умножаем на (x - x_j)/(x_i - x_j)
                denominator = 1.0 / (x_points[i] - x_points[j])

                # Создаем полином (x - x_j) * denominator
                term = np.array([-x_points[j] * denominator, denominator], dtype=float)

                # Умножаем текущий полином на term
                new_poly = np.zeros(len(poly) + 1, dtype=float)
                for k in range(len(poly)):
                    for l in range(2):
                        new_poly[k + l] += poly[k] * term[l]
                poly = new_poly

        # Добавляем вклад от y_i * l_i(x)
        for k in range(len(poly)):
            coefficients[n - 1 - k] += y_points[i] * poly[len(poly) - 1 - k]

    return coefficients

class LagrangeInterpolator:

    def __init__(self, x_points, y_points):

        self.x_points = np.asarray(x_points, dtype=float)
        self.y_points = np.asarray(y_points, dtype=float)
        self.n = len(x_points)

        # Проверка данных
        if len(self.x_points) != len(self.y_points):
            raise ValueError("Количество x и y точек должно совпадать")

        if len(np.unique(self.x_points)) != self.n:
            raise ValueError("Узлы интерполяции должны быть уникальными")

        # Предвычисляем знаменатели для оптимизации
        self.denominators = np.ones(self.n, dtype=float)
        for i in range(self.n):
            denominator = 1.0
            for j in range(self.n):
                if i != j:
                    denominator *= (self.x_points[i] - self.x_points[j])
            self.denominators[i] = denominator

    def __call__(self, x_values):

        x_values = np.asarray(x_values, dtype=float)
        is_scalar = x_values.ndim == 0
        x_values = np.atleast_1d(x_values)

        result = np.zeros_like(x_values, dtype=float)

        for i in range(self.n):
            # Вычисляем числитель для текущего базисного полинома
            numerator = np.ones_like(x_values, dtype=float)
            for j in range(self.n):
                if i != j:
                    numerator *= (x_values - self.x_points[j])

            # Вычисляем базисный полином и добавляем в результат
            result += self.y_points[i] * numerator / self.denominators[i]

        return result[0] if is_scalar else result

    def derivative(self, x_values, order=1):

        # Для производных используем численное дифференцирование
        # Можно было бы аналитически вычислить производную полинома
        h = 1e-6
        x_values = np.asarray(x_values, dtype=float)

        if order == 1:
            return (self(x_values + h) - self(x_values - h)) / (2 * h)
        elif order == 2:
            return (self(x_values + h) - 2 * self(x_values) + self(x_values - h)) / (h ** 2)
        else:
            raise ValueError("Пока поддерживаются только производные 1-го и 2-го порядка")

    def get_coefficients(self):
        return lagrange_coefficients(self.x_points, self.y_points)

    def plot(self, x_min=None, x_max=None, num_points=1000, show_nodes=True):

        if x_min is None:
            x_min = self.x_points.min() - 0.5
        if x_max is None:
            x_max = self.x_points.max() + 0.5

        x_plot = np.linspace(x_min, x_max, num_points)
        y_plot = self(x_plot)

        plt.figure(figsize=(10, 6))
        plt.plot(x_plot, y_plot, 'b-', linewidth=2, label='Интерполяционный полином')

        if show_nodes:
            plt.scatter(self.x_points, self.y_points, color='red', s=100,
                       zorder=5, label='Узлы интерполяции', edgecolors='black')

        plt.xlabel('x', fontsize=12)
        plt.ylabel('L(x)', fontsize=12)
        plt.title(f'Интерполяционный полином Лагранжа степени {self.n-1}', fontsize=14)
        plt.grid(True, alpha=0.3)
        plt.legend()
        plt.tight_layout()
        plt.show()

x_test = [1.5, 2.5, 3.5]
y_interp = lagrange_interpolation(int_points, y1_lagrange_values, x_test)
print("\n Значения полинома Лагранжа в точках 1.5, 2.5 и 3.5: ", y_interp)

interpolator = LagrangeInterpolator(int_points, y1_lagrange_values)
interpolator.plot(x_min=1, x_max=4, num_points=1000)

found_max_value = y_interp[0]
true_max_value = -2.13332856
difference = abs(true_max_value - found_max_value)

print("\n Найденное значение полинома в точке 1.5 : ", found_max_value, "отклонение от истинного значения : ", difference)
